# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (sdd-context)
功能: sdd-context
  @req:r3
  场景: rebuild-embeds-feature-scenarios
    假如 某 spec 目录同时含 spec.toon（含 1 个 feature:true 场景）与 1 个 .feature 文件（含 2 个场景）
    当 执行 sdd index rebuild
    那么 tree.json 中该 spec 的 scenarios 含 3 个场景（toon 与 feature 合并去重）
    而且 feature 来源场景的 req_id 为空

  @req:r3
  场景: get-spec-content-returns-spec-level-scenarios
    假如 tree.json 中某 spec 含 req_id 为空的 spec 级别场景
    当 调用 get_spec_content(spec_id, req_ids)
    那么 返回结果含一个 req_id 为空的额外条目
    而且 该条目含全部 spec 级别场景的 given/when/then 全文

  @req:r3
  场景: non-bdd-spec-unchanged
    假如 某 spec 目录无 .feature 文件
    当 执行 sdd index rebuild 后调用检索工具
    那么 scenarios 仅来自 spec.toon
    而且 检索输出与无 feature 嵌入前完全一致

  @req:r1
  场景: 拒绝非 pageindex 后端值
    假如 用户执行 sdd context --backend {bad_backend}
    当 命令解析 --backend 值
    那么 报错退出
    而且 提示 backend 仅支持 pageindex
    而且 引导配置所需环境变量

  @req:r1
  场景: chat 模型 endpoint 回退复用 OPENAI 值
    假如 LLMAN_SDD_INDEX_CHAT_API_HOST 未设置但 LLMAN_SDD_INDEX_OPENAI_API_HOST 已设置
    当 解析 chat 模型 endpoint
    那么 回退复用 LLMAN_SDD_INDEX_OPENAI_API_HOST 的值

  @req:r1
  场景: 默认 host 为空且未配置时报错
    假如 LLMAN_SDD_INDEX_CHAT_API_HOST 未设置且 LLMAN_SDD_INDEX_OPENAI_API_HOST 也未设置
    当 ChatConfig::from_env() 执行
    那么 返回错误并提示用户配置 LLMAN_SDD_INDEX_CHAT_API_HOST
    而且 不回退到任何可路由地址

  @req:r1
  场景: 显式 host 正常生效
    假如 LLMAN_SDD_INDEX_CHAT_API_HOST 已设置为合法 URL
    当 ChatConfig::from_env() 执行
    那么 正常返回配置
    而且 使用用户提供的值

  @req:r1
  场景: 索引缺失时返回 unavailable 且不回退
    假如 pageindex 索引缺失
    当 执行 sdd context（未显式 --backend）
    那么 返回 quality=unavailable
    而且 qualityNote 含 rebuild 命令
    而且 不回退到任何其它检索方式

  @req:r1
  场景: 配置缺失时给出简洁可操作提示
    假如 LLMAN_SDD_INDEX_CHAT_MODEL 未设置
    当 执行 sdd context
    那么 提示明确列出需设置的变量名与 rebuild 命令
    而且 内容简洁无冗余

  @req:r1
  场景: rebuild 从 IR 构建树索引无需 LLM
    假如 存在多个已解析的 sdd spec
    当 执行 sdd index rebuild --backend pageindex
    那么 生成 tree.json
    而且 构建过程不发起任何 LLM 请求

  @req:r1
  场景: agentic loop 经三工具导航
    假如 chat 模型收到 system prompt 与三工具（list_specs / get_document_structure / get_spec_content）
    当 sdd context 检索执行
    那么 LLM 依次调用工具后输出 direct/related 分类结果

  @req:r1
  场景: 后端隔离不互相降级
    假如 .context/rag/ 已有索引但 .context/pageindex/ 不存在
    当 执行 sdd context --backend pageindex
    那么 返回 quality 为 unavailable 且 errorKind 为 index_missing
    而且 不降级使用 rag 索引

  @req:r2
  场景: rebuild-includes-scenarios
    假如 存在一个 sdd spec，其 spec.toon 含若干 feature:true 的场景
    当 执行 sdd index rebuild --backend pageindex
    那么 生成的 tree.json 中对应 DocNode 的 scenarios 字段非空
    而且 场景含 req_id/id/given/when/then

  @req:r2
  场景: get-document-structure-lists-scenarios
    假如 tree.json 中某 DocNode 含 scenarios 字段
    当 调用 get_document_structure(spec_id)
    那么 返回的每个 req 节点下含 scenarios 列表（仅 id，省 token）

  @req:r2
  场景: get-spec-content-includes-scenarios
    假如 tree.json 中某 DocNode 含 scenarios 字段
    当 调用 get_spec_content(spec_id, req_ids)
    那么 返回的条目含 scenarios 数组
    而且 每个场景含 given/when/then 全文

  @req:r2
  场景: spec-hash-includes-feature
    假如 某 spec 目录下存在 .feature 文件
    当 修改该 .feature 文件后执行 sdd index check
    那么 索引状态为 stale（staleness hash 变化触发）
