# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (sdd-context)
功能: sdd-context
  场景: rebuild-embeds-feature-scenarios
    假如 某 spec 目录同时含 spec.toon（含 1 个 feature:true 场景）与 1 个 .feature 文件（含 2 个场景）
    当 执行 sdd index rebuild
    那么 tree.json 中该 spec 的 scenarios 含 3 个场景（toon 与 feature 合并去重）
    而且 feature 来源场景的 req_id 为空

  场景: get-spec-content-returns-spec-level-scenarios
    假如 tree.json 中某 spec 含 req_id 为空的 spec 级别场景
    当 调用 get_spec_content(spec_id, req_ids)
    那么 返回结果含一个 req_id 为空的额外条目
    而且 该条目含全部 spec 级别场景的 given/when/then 全文

  场景: non-bdd-spec-unchanged
    假如 某 spec 目录无 .feature 文件
    当 执行 sdd index rebuild 后调用检索工具
    那么 scenarios 仅来自 spec.toon
    而且 检索输出与无 feature 嵌入前完全一致
