# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (errors-exit)
功能: errors-exit
  场景: json-错误输出
    假如 llman 二进制已构建
    当 运行 llman sdd show nonexistent --type spec --json
    那么 退出码为 1 且 stdout 为合法 JSON
