# language: zh-CN
# generated by `llman sdd solidify` from spec.toon (errors-exit)
功能: errors-exit
  @req:r2
  场景: json-错误输出
    假如 llman 二进制已构建
    当 运行 llman sdd show nonexistent --type spec --json
    那么 退出码为 1 且 stdout 为合法 JSON

  @req:r1
  场景: 子命令返回错误时打印单行错误并以退出码 1 退出
    假如 llman 二进制已构建
    当 在非交互终端运行 llman sdd show
    那么 退出码为 1
    而且 stderr 包含 Error

  @req:r1
  场景: 非交互终端下 sdd show 无参数时以退出码 1 退出
    假如 llman 二进制已构建
    当 在非交互终端运行 llman sdd show
    那么 退出码为 1
    而且 stderr 包含 Nothing to show

  @req:r1
  场景: 查看不存在的 spec 时正常报错而非 panic
    假如 llman 二进制已构建
    当 运行 llman sdd show nonexistent-spec --type spec
    那么 退出码非零
    而且 stderr 包含 Error

  @req:r2
  场景: 自指跳过演示
    假如 llman 二进制已构建
    当 运行 llman sdd validate errors-exit --no-interactive
    那么 stdout 包含 Full mode
